import { db } from './client.js'
const T = (sql: string) => db.exec(sql)
export function createSchema() {
  T(`CREATE TABLE IF NOT EXISTS org (id TEXT PRIMARY KEY, name TEXT, industry TEXT, contact TEXT, demoData INTEGER)`)
  T(`CREATE TABLE IF NOT EXISTS plan (id TEXT PRIMARY KEY, tier TEXT, storageUsedGB REAL, storageTotalGB REAL, seats INTEGER, seatsUsed INTEGER, validUntil TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS members (id TEXT PRIMARY KEY, name TEXT, email TEXT, role TEXT, dept TEXT, status TEXT, joinedAt TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, memberId TEXT, email TEXT, passwordHash TEXT, role TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS trial_journey (id INTEGER PRIMARY KEY CHECK (id = 1), activated INTEGER, step INTEGER, installedApps TEXT, uninstalledApps TEXT, userInstalledApps TEXT, invitesSent INTEGER, configProgress INTEGER)`)
  T(`CREATE TABLE IF NOT EXISTS trial_applications (id INTEGER PRIMARY KEY AUTOINCREMENT, companyName TEXT NOT NULL, contact TEXT NOT NULL, agreeToTerms INTEGER NOT NULL, createdAt TEXT NOT NULL)`)
  T(`CREATE TABLE IF NOT EXISTS spaces (id TEXT PRIMARY KEY, name TEXT, count INTEGER, health TEXT, reviewCycle INTEGER, archived INTEGER, createdAt TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS docs (id TEXT PRIMARY KEY, spaceId TEXT, title TEXT, type TEXT, category TEXT, status TEXT, owner TEXT, updatedAt TEXT, source TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS connectors (id TEXT PRIMARY KEY, name TEXT, kind TEXT, connected INTEGER, disabled INTEGER, docs INTEGER, lastSyncAt TEXT, config TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS sync_tasks (id TEXT PRIMARY KEY, connectorId TEXT, status TEXT, progress INTEGER, failedCount INTEGER, at TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS knowledge_map (id TEXT PRIMARY KEY, category TEXT, docId TEXT, position TEXT, relations TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS knowledge_site (id TEXT PRIMARY KEY, title TEXT, content TEXT, category TEXT, updatedAt TEXT, status TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS answer_pool (id TEXT PRIMARY KEY, question TEXT, answer TEXT, citations TEXT, confidence INTEGER)`)
  T(`CREATE TABLE IF NOT EXISTS assistants (id TEXT PRIMARY KEY, name TEXT, icon TEXT, desc TEXT, scope TEXT, enabled INTEGER, draft TEXT, version INTEGER)`)
  T(`CREATE TABLE IF NOT EXISTS assistant_versions (id TEXT PRIMARY KEY, assistantId TEXT, version INTEGER, config TEXT, publishedAt TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS chat_sessions (id TEXT PRIMARY KEY, title TEXT, source TEXT, createdAt TEXT, userId TEXT)`)
  T(`CREATE TABLE IF NOT EXISTS chat_messages (id TEXT PRIMARY KEY, sessionId TEXT, role TEXT, content TEXT, answerId TEXT, createdAt TEXT)`)
}
